# Generated by Django 3.1.3 on 2020-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
