# Generated by Django 3.1.3 on 2020-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_devices_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ransomwares',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
