# Generated by Django 3.1.3 on 2020-11-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201111_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ransomwares',
            name='date',
        ),
    ]
