# Generated by Django 3.1.3 on 2020-11-11 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20201111_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='RansomwaresAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=50)),
                ('bitcoinaccount', models.CharField(max_length=200)),
                ('file_formats', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('created', 'Created')], default='waiting', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
