# Generated by Django 3.1.3 on 2020-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ransomwares_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ransomwares',
            name='url',
            field=models.CharField(default='No Link Create Ransomware !', max_length=200),
        ),
    ]
